# Numpy Learning

*These exercises are Quickstart tutorial on numpy.org.*

## 1. Introduction to NumPy
- 다차원 배열(ndarray)을 다루며, 이는 리스트보다 빠르고 효율적임(반복문 없이 가능)
- 벡터 및 행렬 연산 기능을 제공하는 라이브러리
- 수학 연산 함수 제공
- linalg 모듈을 활용한 행렬 연산 가능
- 서로 다른 크기의 배열을 연산할 때 자동으로 크기를 맞춰 연산 가능(Broadcasting)

## 2. Importing NumPy
- Install : pip install numpy
- The standard way to import NumPy : import numpy as np

In [1]:
import numpy as np

## 3. Attributes of an ndarray object

In [2]:
# NumPy's array class is calles 'ndarray'.
a = np.arange(6) # 1차원 배열
print(a)

[0 1 2 3 4 5]


In [3]:
b = np.arange(20).reshape(4, 5) # 2차원 배열
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:
c = np.arange(24).reshape(2, 3, 4) # 3차원 배열
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [5]:
b.shape # For a matrix with n rows and m columns : (n,m)

(4, 5)

In [6]:
b.ndim # the numbr of dimensions of the array

2

In [7]:
b.size # the total number of elements of the array

20

In [8]:
b.dtype # an object describing the type of the elements in the array

dtype('int32')

In [9]:
b.itemsize # the size in bytes of each element of the array

# 배열의 각원소가 차지하는 바이트의 크기를 나타낸다고 함
# 배열의 데이터 타입에 따라 각 원소가 메모리에서 차지하는 크기가 달라지는데
# float64타입은 64비트=8바이트를 차지하고 complex32 타입은 32비트=4바이트를 차지...

4

In [10]:
type(b)

numpy.ndarray

## 4. Creating Array

In [11]:
d = np.array([[1, 2], [3, 4]], dtype=complex)
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [12]:
# create an array full of 0
np.zeros((3, 3))  # 3x3 크기의 0으로 채워진 배열

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# create an array full of 1
np.ones((2, 4))  # 2x4 크기의 1로 채워진 배열

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# create an array whose initial content is random and depends on the state of the memory
np.empty((2, 3)) 

array([[-6.95294368e-310, -1.32635771e-148,  1.27806168e-311],
       [ 1.27806168e-311,  1.13635099e-322,  1.72922976e-322]])

In [15]:
# create an array full of specific number
np.full((2, 2), 7)  # 2x2 크기의 7로 채워진 배열

array([[7, 7],
       [7, 7]])

In [16]:
# create sequences of numbers
np.arange(10)  # 0부터 9까지의 배열

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# 랜덤 값 배열 생성
np.random.rand(3, 3)  # 3x3 크기의 랜덤 실수 배열

array([[0.69781036, 0.96225211, 0.12288586],
       [0.63185289, 0.78839411, 0.1366538 ],
       [0.99833116, 0.73558923, 0.2504434 ]])

## 6. Basic operations

In [18]:
a = np.array([20, 30, 40, 50])
b = np.arange(4) # 'b' ouput: array([0, 1, 2, 3])
c = a - b
c

array([20, 29, 38, 47])

In [19]:
b ** 2 
# '*' : 각 원소 곱, 행렬 곱 가능(Elementwise multiplication)
# '**' : 각 원소 제곱 (Elementwise power)

array([0, 1, 4, 9])

In [20]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [21]:
a < 35

array([ True,  True, False, False])

In [22]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A @ B # @연산자, .dot()메서드 둘다 행렬 곱셈이지만 다차원 연산시 차이 발생할 수 있음 @가 일반적인 결과 

array([[5, 4],
       [3, 4]])

In [23]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [24]:
from numpy import random # NumPy의 난수 생성 모듈 호출
from numpy.random import default_rng # Random Generator 

In [25]:
rng = default_rng(1) # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rng.random((2, 3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [26]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [27]:
# a += b  
# UFuncTypeError : b is not automatically converted to integer type

In [28]:
from math import pi 

In [29]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [30]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [31]:
c.dtype.name

'float64'

In [32]:
d = np.exp(c*1j) # np.exp() : 자연상수 e 계산 함수
                 # c*1j : 복소수 배열, 1j는 python에서 복소수의 허수 단위
                 # 즉, 오일러 공식
print(d)
d.dtype.name

[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]


'complex128'

In [33]:
a = rng.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [34]:
a.sum()

3.1057109529998157

In [35]:
a.max()

0.8277025938204418

In [36]:
a.min()

0.027559113243068367

In [37]:
# specifying the axis parameter, you can apply an aperation along the specified axis of an array
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
b.sum(axis=0) # 각 열의 합

array([12, 15, 18, 21])

In [39]:
b.min(axis=1) # 각 행의 최소값

array([0, 4, 8])

In [40]:
b.cumsum(axis=1) # axis=1 : 행 기준 누적합 (왼쪽에서 오른쪽으로 더함)
                 # axis=0 : 열 기준 누적합 (위쪽에서 아래쪽으로 더함)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

## 6. Universal funtions
- NumPy procides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (ufunc)

In [41]:
B = np.arange(3)
B

array([0, 1, 2])

In [42]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [43]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [44]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

## 7. Indexing, Slicing and iterating

In [45]:
a = np.arange(10)**3
# 'a' output : array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])
# 각 요소에 세제곱 1차원 배열 
a[2] # 인덱스는 0부터 시작, 인덱스 2에 해당하는 값 가져옴

8

In [46]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [47]:
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [48]:
# reversed a
a[ : :-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

## 8. Changing the shape of an array

In [49]:
a = np.floor(10 * rng.random((3, 4)))
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [50]:
a.ravel()  # returns the array, flattened

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [51]:
a.reshape(6, 2)  # returns the array with a modified shape

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [52]:
a.T # returns the array, transposed
result = print(a.T) # 결과를 변수로 저장하고 출력
result

[[3. 1. 7.]
 [7. 4. 2.]
 [3. 2. 4.]
 [4. 2. 9.]]


In [53]:
print(a.T.shape)
print(a.shape)

(4, 3)
(3, 4)


In [54]:
a = np.floor(10*rng.random((2,2)))
b = np.floor(10*rng.random((2,2)))
print(a)
print(b)

[[9. 7.]
 [5. 2.]]
[[1. 9.]
 [5. 1.]]


In [55]:
np.vstack((a,b))

array([[9., 7.],
       [5., 2.],
       [1., 9.],
       [5., 1.]])

In [56]:
np.hstack((a,b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [57]:
from numpy import newaxis
np.column_stack((a,b)) 

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [58]:
a = np.array([4., 2.])
b = np.array([3., 8.])
np.column_stack((a, b))  # returns a 2D array

array([[4., 3.],
       [2., 8.]])

In [59]:
np.hstack((a, b))        # the result is different

array([4., 2., 3., 8.])

In [60]:
a[:, newaxis]  # view `a` as a 2D column vector

array([[4.],
       [2.]])

In [61]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [62]:
np.hstack((a[:, newaxis], b[:, newaxis]))  # the result is the same

array([[4., 3.],
       [2., 8.]])

In [63]:
np.r_[1:4, 0, 4]
# r_ and c_ are similar to vstack and hstack in their default behavior, but allow for an optional argument giving the number of the axis along which to concatenate

array([1, 2, 3, 0, 4])

## 10. "Automatic" reshaping
To change the dimensions of an array, you can omit one of the sizes which will then be deduced automatically


In [64]:
a = np.arange(30)
b = a.reshape((2, -1, 3))  # -1 means "whatever is needed"
b.shape

(2, 5, 3)

In [65]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

# ch1_Python for Linear Algebra
 ## Numpy를 이용한 동력계 문제 해결
 - 동력계(Dynamic System)는 시간에 따라 값이 변하는 변수들의 유한 집합
 - 어떤 시점(t)에서의 변수의 값을 변수의 상태(state of variable)라 함
 - 이때 생성된 Vector를 동력계의 상태(state of the dynamical system)라 함
 - *예시: 경쟁관계에 있는 두 개의 TV 채널 1과 채널 2는 초기 시장 점유율이 50%로 동일하다. 1년마다 채널 1은 채널 2의 시청률 10%를 잠식하고, 채널 2는 채널 1의 시청률 20%를 잠식한다고 가정하자. 5년 후 각 채널의 시장 점유율은 어떻게 될 것인가?*

In [66]:
matrix_a = np.array([[0.8, 0.1],
                       [0.2, 0.9]])
init_vector = np.array([0.5, 0.5])

In [67]:
x0 = init_vector.T
print(x0)

[0.5 0.5]


In [68]:
# 1년 후
x1 = matrix_a.dot(x0)
print(x1)

[0.45 0.55]


In [69]:
# 2년 후
x2 = matrix_a.dot(x1)
print(x2)

[0.415 0.585]


In [70]:
def x(t):
    matrix_a = np.array([[0.8, 0.1],
                       [0.2, 0.9]])
    init_vector = np.array([0.5, 0.5])

    if t == 0: 
        xt = init_vector
        return xt
    else:
        xt = init_vector
        for i in range(t):
            xt = matrix_a.dot(xt)
        return xt

print('초기 각 채널 점유율 : ', x(0))
print('1년 후 각 채널 점유율 : ', x(1))
print('2년 후 각 채널 점유율 : ', x(2))

print('5년 후의 각 채널 점유율 :', x(5))
print('100년 후의 각 채널 점유율 : ', x(100))

초기 각 채널 점유율 :  [0.5 0.5]
1년 후 각 채널 점유율 :  [0.45 0.55]
2년 후 각 채널 점유율 :  [0.415 0.585]
5년 후의 각 채널 점유율 : [0.361345 0.638655]
100년 후의 각 채널 점유율 :  [0.33333333 0.66666667]


# Homework

## 과제1
 - 3 X 3 Matrix A가 아래와 같이 정의되었다. 이를 바탕으로 AB(행렬곱)가 다음과 같을 때, B를 구하는 코드를 작성하시오.

In [84]:
A = np.array([[1, 0, 2],
              [0, 1, 1],
              [1, 2, 2]])

# 단위행렬 E를 만드는 코드
E = np.identity(3)

# C = A - 2E 계산
C = A - 2 * E
C_inverse = np.linalg.inv(C)

# B = C⁻¹ × (-A)
B = np.dot(C_inverse, -A)

print(B)

[[ 0.  -2.  -1. ]
 [-0.5  0.  -0.5]
 [-0.5 -1.  -1.5]]


## 과제2
- 아래의 선형계를 푸시오. 만약 문제가 해결되지 않을 경우(Error가 발생할 경우), 예외 처리 구문을 활용한 후 왜 Error가 발생하였는지 이유를 출력하시오.


In [72]:
# 2-1)
A = np.array([
    [ 2, -1, -3],
    [-1, -2, -3],
    [ 1,  1,  4]])

b = np.array([ 2, -1,  1 ])

try:
    # A x = b 를 풀어서 x를 구합니다.
    x = np.linalg.solve(A, b)
    # 결과 출력
    print(f"해: x = {x[0]}, y = {x[1]}, z = {x[2]}")
except np.linalg.LinAlgError as e:
    # 오류가 발생한 경우
    print("Error가 발생하였습니다.")
    print("오류 메시지:", e)
    print("오류 원인: 행렬 A가 역행렬을 갖지 못하는 특이(singular) 행렬이거나, "
          "해가 무수히 많거나 없는 경우 등으로 인해 발생할 수 있습니다.")

해: x = 1.0, y = -0.0, z = 0.0


In [73]:
# 2-2)
A = np.array([
    [ 2, -1, -3],
    [-4, 2, 6],
    [ 3,  1,  4]])

b = np.array([ 2, -1,  1 ])

try:
    # A x = b 를 풀어서 x를 구합니다.
    x = np.linalg.solve(A, b)
    # 결과 출력
    print(f"해: x = {x[0]}, y = {x[1]}, z = {x[2]}")
except np.linalg.LinAlgError as e:
    # 오류가 발생한 경우
    print("Error가 발생하였습니다.")
    print("오류 메시지:", e)
    print("오류 원인: 행렬 A가 역행렬을 갖지 못하는 특이(singular) 행렬이거나, "
          "해가 무수히 많거나 없는 경우 등으로 인해 발생할 수 있습니다.")

Error가 발생하였습니다.
오류 메시지: Singular matrix
오류 원인: 행렬 A가 역행렬을 갖지 못하는 특이(singular) 행렬이거나, 해가 무수히 많거나 없는 경우 등으로 인해 발생할 수 있습니다.


## 과제 3
- 아래 그림과 같이, n by n Matrix를 입력 받았을 때, 해당 Matrix를 1 by 𝑛^2의 Matrix로 변환하는 함수를 작성하시오.(단, Numpy 내장 함수를 사용하지 말 것)

In [74]:
def f(array):
    return np.array([i for row in array for i in row])

f(np.array([[1,2], [2,3]]))

array([1, 2, 2, 3])

In [75]:
f(np.array([[1,2,3], [2,3,4], [3,4,5]]))

array([1, 2, 3, 2, 3, 4, 3, 4, 5])

## 과제4
- 꼬리표가 달린 사자가 영역 1과 영역 2에서 생활한다고 가정하자. 과거의 데이터를 바탕으로, 사자의 월간 이동 패턴은 아래의 그림과 같이 표현된다. 𝑡=0일 때 사자를 영역 2에 풀어놓았을 때, 2개월 간 사자의 예상 위치를 추적하라.(t는 개월수이다.)

In [89]:
def init(t):
   
    P = np.array([
        [0.6, 0.3],  
        [0.4, 0.7]   
    ])
    
    # 초기 상태 벡터 (사자가 영역 2에서 시작)
    X_t = np.array([[0], [1]])  # (2×1)
    
    # t개월 후 상태 계산
    for _ in range(t):
        X_t = P.dot(X_t)  # ✅ 반복적으로 행렬 곱 수행
    
    return X_t

# 결과 출력
print(init(2))

[[0.39]
 [0.61]]


## 과제5
- 과제 4를 바탕으로, t개월 후 사자의 예상 위치를 추적하는 함수를 작성하여 10개월 후 사자의 예상 위치를 추적하라. 단, 이번엔 사자를 영역 1에 풀어놓았다.

In [90]:
def x(t):
    
    P = np.array([
        [0.6, 0.3],  
        [0.4, 0.7]   
    ])
    
    # 영역 1에서 시작
    X_t = np.array([[1], [0]])  # (2×1)

    # t개월 후 상태 계산
    for _ in range(t):
        X_t = P.dot(X_t) 
    
    return X_t

x(10)

array([[0.4285748],
       [0.5714252]])